[package]
name = "mlsmpm"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
csv = "1.1.6"
rayon = "1.7.0"
rand = "0.8.5"
chrono = "0.4.26"
mlsmpm_macro = { path = "../mlsmpm_macro" }
