import { DefaultEventsMap } from "@socket.io/component-emitter";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { io, Socket } from 'socket.io-client';

export default function MPMHome() {
	const socketRef = useRef<Socket<DefaultEventsMap, DefaultEventsMap> | null>(null);

	useEffect(() => {
		console.log('Connectinng..');
		socketRef.current = io();

		socketRef.current.on('particles-data', (particles) => {
			console.log(particles);
		});

		return () => {
			console.log('Disconnecting..');
			socketRef.current?.disconnect();
		};
	}, []);

	return (<>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			<button onClick={() => {
				socketRef.current?.emit('requestMPM');
			}}>aaa</button>
		</main>
	</>)
}